---
title: "map_abundance"
author: "Yiheng Du"
date: "2023-12-10"
output: html_document
---

# Load the relevant packages

```{r, include=FALSE}
library(readxl)
library(tidyverse)
library(openxlsx)
library(ggpubr)
library(maps)
library(broom)
library(reshape2)
library(pheatmap)
```

# Import loaction and environment file

```{r}
raw_data <- read.csv('./dwde2xd2.csv')
```


```{r}
raw_data
```








```{r}
data <- raw_data %>% select('env1_split_1','abundance','lon','lat') %>% drop_na()

# as.numeric(gsub("%", "", df$percentage_column)) / 100
data$abundance <- as.numeric(gsub("%", "", data$abundance)) / 100

```



```{r}
color_scheme <- c("#AFD888", "#63ADD0", "#FF4540", "#D836C4", "#EE6B9E", "#FF8F40", "#FFFA73", "#00A779")
world_map <- map_data("world")
# reduce the NA in last column
# data <- data[complete.cases(data),]
ggplot() +
  geom_polygon(data = world_map,
               aes(x = long, y = lat, group = group),
               fill = "lightgray", color = "gray") +
  geom_point(data = data, aes(x = lon,
                              y = lat, 
                              fill=factor(env1_split_1),
                              size = abundance), 
             alpha = 0.5, shape = 21, 
             color = 'grey40', stroke = 0.5) +
  scale_size_continuous(name = "Node size for relative abundance", guide = guide_legend(override.aes = list(color = "black",fill="black"))) +
  scale_fill_manual(values = color_scheme, 
                  name = "Node color for sample environmental type", guide = guide_legend(override.aes = list(size = 6)))
  labs(x = "longitude", y = "latitude") +
  theme_bw() +
  NULL
ggsave("world.pdf",units = "in",width = 17.27, height = 6.8)
```








